const DATE_TIME_FORMAT = 'YYYY-MM-DD HH:mm:ss'
const DATE_FORMAT = 'YYYY-MM-DD'
const TIME_FORMAT = 'HH:mm:ss'

const TIME_12HOUR_DISPLAY_FORMAT = 'HH:mm A'
const DATE_DISPLAY_FORMAT = "DD-MM-YYYY"
const DATE_TIME_12HOUR_DISPLAY_FORMAT = 'DD-MM-YYYY HH:mm A'
const TIMEZONE_DISPLAY_FORMAT = 'Z'
const SHORT_MONTH_YEAR_DISPLAY_FORMAT = 'MMM YYYY'
const MONTH_YEAR_DISPLAY_FORMAT = 'MMMM YYYY'

export {
  DATE_TIME_FORMAT,
  DATE_FORMAT,
  TIME_FORMAT,
  DATE_DISPLAY_FORMAT,
  DATE_TIME_12HOUR_DISPLAY_FORMAT,
  TIME_12HOUR_DISPLAY_FORMAT,
  TIMEZONE_DISPLAY_FORMAT,
  MONTH_YEAR_DISPLAY_FORMAT,
  SHORT_MONTH_YEAR_DISPLAY_FORMAT,
}