const DATE_TIME_FORMAT = 'YYYY-MM-DD HH:mm:ss'
const DATE_FORMAT = 'YYYY-MM-DD'
const TIME_FORMAT = 'HH:mm:ss'

const TIME_12HOUR_DISPLAY_FORMAT = 'HH:mm A'
const DATE_TIME_12HOUR_DISPLAY_FORMAT = 'DD-MM-YYYY HH:mm A'
const TIMEZONE_DISPLAY_FORMAT = 'Z'

export {
  DATE_TIME_FORMAT,
  DATE_FORMAT,
  TIME_FORMAT,
  DATE_TIME_12HOUR_DISPLAY_FORMAT,
  TIME_12HOUR_DISPLAY_FORMAT,
  TIMEZONE_DISPLAY_FORMAT,
}